dataset_name: "pancreas"
num_classes: 17
num_batches: 8
classes: ["alpha", "beta", "ductal", "acinar", "delta", "gamma", "activated_stellate", "alpha_er", "nan", "endothelial", "quiescent_stellate", "beta_er", "macrophage", "mast", "epithelial", "schwann", "epsilon"]
batches: ["pancreas_indrop3", "pancreas_celseq2", "pancreas_smartseq2", "pancreas_indrop1", "pancreas_indrop2", "pancreas_celseq", "pancreas_indrop4", "pancreas_fluidigmc1"]
train_classes: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16]
val_batches: [0, 1, 2, 4, 5, 6, 7]
val_classes: [7]
val_batches: [3]
length_train: 11237
length_none: 2793
length_val_type: 448
length_val_batch: 1937
# tokensizer
vocab_size: 14900
num_special_tokens: 5
num_genes: 14895
cls_idx: 1
padding_idx: 3
mask_idx: 4
#
num_crops_g: 2
min_length_g: 128
mean_length_g: 256
max_length_g: 384
noise_ratio_g: 0.02
dropout_p_g: 0.1
#
num_crops_l: 2
min_length_l: 64
mean_length_l: 128
max_length_l: 256
noise_ratio_l: 0.02
dropout_p_l: 0.1
#
length_dist: "sample"
log_count: True
count_temp: 5
zero_prop: 0.2
#
mask_prop_gene: 0.15
mask_prop_count: 0.15
#
batch_size: 8
pred_start_epoch: 0
